In [15]:
    import jax.numpy as np
    import jax as jax


In [22]:
emp = np.empty([5,4], dtype='float32')
sub = np.array([[1,2,3,4],[6,7,8,9]], dtype='float32')
emp, sub

(DeviceArray([[0., 0., 0., 0.],
              [0., 0., 0., 0.],
              [0., 0., 0., 0.],
              [0., 0., 0., 0.],
              [0., 0., 0., 0.]], dtype=float32),
 DeviceArray([[1., 2., 3., 4.],
              [6., 7., 8., 9.]], dtype=float32))

In [26]:
emp = jax.ops.index_update(emp, jax.ops.index[1:3], sub)
emp

DeviceArray([[0., 0., 0., 0.],
             [1., 2., 3., 4.],
             [6., 7., 8., 9.],
             [0., 0., 0., 0.],
             [0., 0., 0., 0.]], dtype=float32)

In [24]:
sub[jax.ops.index[0:2]]

DeviceArray([[1., 2., 3., 4.],
             [6., 7., 8., 9.]], dtype=float32)